#---------------------STEPS------------
# para iniciar um restore do grafana
# 1- certifique que a pasta /volumes/db contenha o grafana.db
# 2- certifique que a pasta /volumes/ini contenha o grafabna.ini
# 5- rode o compose

version: "3"
services:
  database:
    image: grafana/grafana:latest
    container_name: grafana_cntr
    networks:
      network1:
    ports:
      - 3000:5000
    volumes:
      # tem que bindar so o arquivo do ini pois o grafana cria outra estrutura anterior, 
      # se bindar toda a pasta ele sobreescreve a estrutura anterior criada pelo grafana
      - ./volumes/ini/grafana.ini:/etc/grafana/grafana.ini
      - ./volumes/db:/var/lib/grafana
networks:
  network1:
      external:
        name: network1