version: "3"
services:
  database:
    image: datarhei/restreamer:latest
    container_name: restreamer
    networks:
      network1:
    environment:
      - "RS_USERNAME=admin"
      - "RS_PASSWORD=datarhei"
    ports:
      - 8080:8080
      - 1932:1932
    volumes:
      - /var/local_volumes/restream/db:/restreamer/db
      - /var/local_volumes/restream/core/data:/core/data
      - /var/local_volumes/restream/core/config:/core/config

networks:
  network1:
      external:
        name: network1