version: "3"
services:
  database:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver_cntr
    networks:
      network1:
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=qwerty333"
      - "POSTGRES_DB=postgres"
    ports:
      - 1010:8978
    volumes:
      - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace
networks:
  network1:
      external:
        name: network1