version: '3.7'

services:
  elasticsearh:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"