version: "2"

services:
  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    - ./templates:/usr/share/nginx/html
    - ./sites-enabled:/etc/nginx/sites-enabled
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./certificate:/etc/certificate
    ports:
    - "8080:80"
    - "443:443"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=443
    pull_policy: build
    networks:
      network:


networks:
  network:
      external:
        name: connect