version: '3.6'
services:

  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Xo%ezZv#K6uF9e@
    volumes:
      - /var/docker_volumes/sql_server/data:/var/opt/mssql/data